import { readFileSync, writeFileSync } from "node:fs";
import ts from "typescript";

const SOURCE_FILE = "src/data/docs.ts";
const OUTPUT_FILE = "src/generated/doc-seo.ts";
const sourceText = readFileSync(SOURCE_FILE, "utf8");
const sourceFile = ts.createSourceFile(SOURCE_FILE, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
const initializers = new Map();

sourceFile.statements.forEach((statement) => {
  if (!ts.isVariableStatement(statement)) return;
  statement.declarationList.declarations.forEach((declaration) => {
    if (ts.isIdentifier(declaration.name) && declaration.initializer) {
      initializers.set(declaration.name.text, declaration.initializer);
    }
  });
});

const relevantProperties = new Set(["slug", "title", "summary", "children", "pages"]);
const propertyName = (name) => {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name)) return name.text;
  throw new Error(`Unsupported property name in ${SOURCE_FILE}`);
};

const evaluate = (expression) => {
  if (ts.isStringLiteral(expression) || ts.isNoSubstitutionTemplateLiteral(expression)) {
    return expression.text;
  }
  if (ts.isArrayLiteralExpression(expression)) {
    return expression.elements.map(evaluate);
  }
  if (ts.isObjectLiteralExpression(expression)) {
    const value = {};
    expression.properties.forEach((property) => {
      if (!ts.isPropertyAssignment(property)) return;
      const name = propertyName(property.name);
      if (relevantProperties.has(name)) {
        value[name] = evaluate(property.initializer);
      }
    });
    return value;
  }
  if (ts.isIdentifier(expression)) {
    const initializer = initializers.get(expression.text);
    if (!initializer) throw new Error(`Could not resolve ${expression.text} in ${SOURCE_FILE}`);
    return evaluate(initializer);
  }
  if (ts.isAsExpression(expression) || ts.isSatisfiesExpression(expression) || ts.isParenthesizedExpression(expression)) {
    return evaluate(expression.expression);
  }
  throw new Error(`Unsupported SEO metadata expression (${ts.SyntaxKind[expression.kind]}) in ${SOURCE_FILE}`);
};

const docSectionsInitializer = initializers.get("docSections");
if (!docSectionsInitializer) {
  throw new Error(`Could not find docSections in ${SOURCE_FILE}`);
}

const seoSections = evaluate(docSectionsInitializer);
if (!Array.isArray(seoSections) || seoSections.length === 0) {
  throw new Error(`No documentation sections were generated from ${SOURCE_FILE}`);
}

const output = [
  "// Auto-generated by generate-doc-seo.mjs",
  "import type { DocSeoSection } from \"../types/doc-seo\";",
  `export const docSeoSections = ${JSON.stringify(seoSections, null, 2)} as const satisfies readonly DocSeoSection[];`,
  "",
].join("\n");

writeFileSync(OUTPUT_FILE, output, "utf8");
console.log(`Documentation SEO index generated (${OUTPUT_FILE}): ${seoSections.length} sections`);
